### ISSUE TITLE
Add prebuilt web-eid.js file

### ISSUE THREAD

**Issue by joellimberg** [web-eid/web-eid.js#25]
From the readme, under **Installation** → **Without a module system**: ”Use the dist/iife build. It exposes the webeid object globally.”

The “dist/iife build” is not actually in the repo or under [releases](https://github.com/web-eid/web-eid.js/releases).

It would be clearer if there was a clear link to a browser-usable js file. Currently, the built files can only be found under GitHub action build artifacts (eg https://github.com/web-eid/web-eid.js/actions/runs/2058087830)

**Comment by Muzosh** [comment]
I'm not sure if this helps you, but you can build it yourself by cloning the repository and following this: https://github.com/web-eid/web-eid.js#development.

**Comment by joellimberg** [comment]
Yeah, I figured out how to get the built file (it seems to be easiest to use the [build artifacts](https://github.com/web-eid/web-eid.js/actions/runs/1779627482), although finding the correct stable release is still not trivial).

I just think the repo should also provide usable and _official_ distribution files to make it easier for other implementers :)

**Comment by taneltm** [comment]
Thanks @joellimberg for pointing it out!

The current setup is intentional:
- It avoids scenarios where someone could either accidentally or maliciously send a PR with working source-code, but broken `dist/iife/web-eid.js`. There could be a CI step to check for this mismatch, but there are better options.
- If the pre-built version is in the repo, then `dist/iife/web-eid.js` should always match the source, which might not necessarily be the latest stable version.

The place to download a stable pre-built version of the library should be under <https://github.com/web-eid/web-eid.js/releases>. However, thanks you your comment, I now noticed that the pre-built versions are not there and that's definitely something we should fix!

**Comment by joellimberg** [comment]
Yep, it doesn't really matter where exactly the built files are, as long they exist and are linked from the README :)

**Comment by mrts** [comment]
The pre-built package is now attached to release [v2.0.1](https://github.com/web-eid/web-eid.js/releases/tag/v2.0.1) and README has been updated with the corresponding link.

Thanks for pointing this out!
